return {
    {
        "mason-org/mason.nvim",
        build = ":MasonUpdate",
        cmd = "Mason",
        keys = {
            {
                "<leader>mm",
                "<cmd>Mason<cr>",
                desc = "go to declaration",
            },
        },
        opts = {
            ui = {
                check_outdated_packages_on_open = true,
                border = Adev.ui.border,
            },
        },
    },
    {
        "jay-babu/mason-null-ls.nvim",
        dependencies = "mason-org/mason.nvim",
        opts = {
            ensure_installed = {
                "gitlint",
                "actionlint",
                "cfn_lint",
                "checkmake",
                "hadolint",
                "yamllint",
                "djlint",
                "duster",
                "black",
                "cmake_format",
                "isort",
                "blade_formatter",
                "bibclean",
                "shellharden",
                "pretty_php",
                "asmfmt",
                "rustywind",
                "shfmt",
                "cbfmt",
                "deno",
                "sql_formatter",
                "prettier",
                "gitrebase",
                "proselint",
                "npm-groovy-lint",
                "phpcs",
                "phpmd",
                "prettierd",
                "pyre",
                "alex",
                "stylua",
            },
        },
    },
    {
        "mason-org/mason-lspconfig.nvim",
        dependencies = "mason-org/mason.nvim",
        opts = {
            automatic_enable = false,
            ensure_installed = {
                "astro",
                "csharp_ls",
                "gopls",
                "eslint",
                "svelte",
                "biome",
                "vue_ls",
                "emmet_ls",
                "bashls",
                "clangd",
                "cmake",
                "cssmodules_ls",
                "dockerls",
                "docker_compose_language_service",
                "html",
                "jsonls",
                "pyre",
                "pylsp",
                "pyright",
                "rust_analyzer",
                "sqlls",
                "ts_ls",
                "cssls",
                "css_variables",
                "prismals",
                "tailwindcss",
                "taplo",
                "zls",
                "yamlls",
                "lemminx",
                "texlab",
                "glsl_analyzer",
                "jdtls",
                "intelephense",
                "lua_ls",
            },
        },
    },
}
