local defaults = require "adev.defaults"
local utils = require "adev.utils"

local OnBoarding = {
    init = utils.adev_path .. "/init.lua",
    init_opts = utils.adev_path .. "/lua/adev/init-opts.lua",
}

function OnBoarding:is_new()
    local opts = not (
        vim.fn.filereadable(self.init) == 1 and vim.fn.filereadable(self.init_opts) == 1
    )
    if opts then
        return opts
    end

    local currents = require "adev.init-opts" or {}

    local same_config = not utils.compare_keys(defaults, currents)

    return same_config
end

--- Restart Neovim after a delay
---@param delay number? Delay in milliseconds
function OnBoarding.restart_neovim(delay)
    vim.defer_fn(function()
        if vim.fn.has "nvim-0.12.0" == 1 then
            vim.cmd [[ restart ]]
        else
            vim.cmd [[ qa! ]]
        end
    end, delay or 1500)
end

function OnBoarding:onboarding()
    if not self:is_new() then
        return
    end

    local opts_lines = {
        "-- Auto-generated by adev configuration\n",
        "-- Configuration options for adev.nvim\n",
        "-- NOTE: this file ignored by git\n",
        "return ",
        vim.inspect(defaults),
        "\n",
    }

    local init_lines = {
        "-- Auto-generated by adev configuration\n",
        "-- Main setup file for adev.nvim\n",
        "local opts = require('adev.init-opts')\n",
        'require("adev").setup(opts)\n',
        "\n",
    }

    -- Single pcall for all file operations
    local success, err = pcall(function()
        utils.write_file(self.init_opts, opts_lines)
        utils.write_file(self.init, init_lines)
    end)

    if success then
        utils.notify "adev.nvim configuration created"
        self.restart_neovim()
    else
        utils.err_notify("Save failed: " .. tostring(err))
        return
    end
end

function OnBoarding.edit_config()
    vim.cmd("edit " .. OnBoarding.init_opts)
end

return OnBoarding
