local defaults = require "adev.defaults"
local utils = require "adev-common.utils"

local OnBoarding = {
    init = utils.files:get_config_file "/init.lua",
    init_opts = utils.files:get_config_file "/lua/adev/init-opts.lua",
}

--- checks if current config has differences than the default config
--- @return boolean
function OnBoarding.config_changed()
    local status, currents = pcall(require, "adev.init-opts")
    if not status then
        return true
    end
    return not utils.compare_keys(defaults, currents)
end

--- checks if the user is new and haven't generated config yet
---@return boolean - if `true` then user is new
function OnBoarding:first_time()
    local config_exists = not (
        utils.files.file_exists(self.init) and utils.files.file_exists(self.init_opts)
    )
    return config_exists
end

--- Restart Neovim after a delay
--- @param delay number? Delay in milliseconds
function OnBoarding.restart_neovim(delay)
    delay = delay or 1500

    utils.notify("restarting neovim in " .. delay .. "ms", vim.log.levels.TRACE)
    vim.defer_fn(function()
        if vim.fn.has "nvim-0.12.0" == 1 then
            vim.cmd [[ restart ]]
        else
            vim.cmd [[ qa! ]]
        end
    end, delay)
end

--- onboarding a new user by generating a new config
--- init.lua and init-opts.lua
function OnBoarding:onboarding()
    local config = defaults
    if not self:first_time() then
        if self.config_changed() then
            --- we need to merge the two configs then
            local status, current = pcall(require, "adev.init-opts")
            if not status then
                current = {}
            end
            -- BUG: not fully working
            ---@type SetupOpts
            config = vim.tbl_deep_extend("force", defaults, current)
            for key in pairs(config) do
                if defaults[key] == nil then
                    config[key] = nil
                end
            end
        else
            return
        end
    end

    local opts_lines = {
        "-- Auto-generated by adev configuration\n",
        "-- Configuration options for adev.nvim\n",
        "-- NOTE: this file ignored by git\n",
        "---@type SetupOpts\n",
        "return ",
        vim.inspect(config),
        "\n",
    }

    local init_lines = {
        "-- Auto-generated by adev configuration\n",
        "-- Main setup file for adev.nvim\n",
        "local status, opts = pcall(require, 'adev.init-opts')\n",
        "if status then \n",
        '\trequire("adev").setup(opts)\n',
        "else\n",
        '\tvim.notify("Failed to load adev config: " .. tostring(opts), vim.log.levels.ERROR)\n',
        "end\n",
        "\n",
    }

    local success, err = pcall(function()
        utils.files.write_file(self.init_opts, opts_lines)
        utils.files.write_file(self.init, init_lines)
    end)

    if success then
        utils.notify "adev.nvim configuration created"
        self.restart_neovim()
    else
        utils.err_notify("Save failed: " .. tostring(err))
        return
    end
end

function OnBoarding.edit_config()
    utils.files.open_file(OnBoarding.init_opts)
end

return OnBoarding
