local adev_utils = require "adev.utils"
local defaults = require "adev.defaults"

local utils = require "adev.onboarding.utils"

local OnBoarding = {
    init = adev_utils:get_config_file "/init.lua",
    init_opts = adev_utils:get_config_file "/lua/adev/init-opts.lua",
}

--- checks if the user is new and if config is outdated
---@return boolean - if `true` then user is new or config is outdated
function OnBoarding:is_new()
    local config_exists = (utils.file_exists(self.init) and utils.file_exists(self.init_opts))

    local status, currents = pcall(require, "adev.init-opts")
    if not status then
        currents = {}
    end
    local config_changed = adev_utils.compare_keys(defaults, currents)

    return (config_exists and config_changed)
end

--- Restart Neovim after a delay
---@param delay number? Delay in milliseconds
function OnBoarding.restart_neovim(delay)
    vim.defer_fn(function()
        if vim.fn.has "nvim-0.12.0" == 1 then
            vim.cmd [[ restart ]]
        else
            vim.cmd [[ qa! ]]
        end
    end, delay or 1500)
end

--- onboarding a new user by generating a new config
--- init.lua and init-opts.lua
function OnBoarding:onboarding()
    if self:is_new() then
        return
    end

    local opts_lines = {
        "-- Auto-generated by adev configuration\n",
        "-- Configuration options for adev.nvim\n",
        "-- NOTE: this file ignored by git\n",
        "return ",
        vim.inspect(defaults),
        "\n",
    }

    local init_lines = {
        "-- Auto-generated by adev configuration\n",
        "-- Main setup file for adev.nvim\n",
        "local status, opts = pcall(require, 'adev.init-opts')\n",
        "if status then \n",
        '\trequire("adev").setup(opts)\n',
        'end\n',
        "\n",
    }

    -- Single pcall for all file operations
    local success, err = pcall(function()
        adev_utils.write_file(self.init_opts, opts_lines)
        adev_utils.write_file(self.init, init_lines)
    end)

    if success then
        adev_utils.notify "adev.nvim configuration created"
        self.restart_neovim()
    else
        adev_utils.err_notify("Save failed: " .. tostring(err))
        return
    end
end

function OnBoarding.edit_config()
    vim.cmd("edit " .. OnBoarding.init_opts)
end

return OnBoarding
