return {
    {
        "williamboman/mason.nvim",
        build = ":MasonUpdate",
        cmd = "Mason",
        event = require("abdellatifdev.consts").events.pre,
        opts = {
            ui = {
                check_outdated_packages_on_open = true,
                border = "none",
            },
        },

    },
    {
        "jay-babu/mason-nvim-dap.nvim",
        event = require("abdellatifdev.consts").events.pre,
        after = "williamboman/mason.nvim",
        opts = {
            ensure_installed = {
                "bash-debug-adapter",
                "chrome-debug-adapter",
                "codelldb",
                "debugpy",

            }
        }
    },
    {
        "jay-babu/mason-null-ls.nvim",
        event = require("abdellatifdev.consts").events.pre,
        after = "williamboman/mason.nvim",
        dependencies = {
            "williamboman/mason.nvim",
            "nvimtools/none-ls.nvim",
        },
        opts = {
            ensure_installed = {
                "gitlint",
                "actionlint",
                "cfn_lint",
                "checkmake",
                "hadolint",
                "yamllint",
                "djlint",
                "duster",
                "black",
                "cmake_format",
                "isort",
                "blade_formatter",
                "bibclean",
                "shellharden",
                "pretty_php",
                "asmfmt",
                "rustywind",
                "shfmt",
                "cbfmt",
                "deno",
                "sql_formatter",
                "prettier",
                "gitrebase",
                "proselint",
                "npm-groovy-lint",
                "phpcs",
                "phpmd",
                "prettierd",
                "pyre",
                "alex",
            }
        }
    },
    {
        "williamboman/mason-lspconfig.nvim",
        event = require("abdellatifdev.consts").events.pre,
        after = "williamboman/mason.nvim",
        opts = {
            automatic_enable = false,
            ensure_installed = {
                "astro",
                "csharp_ls",
                "gopls",
                "eslint",
                "svelte",
                "slint_lsp",
                "svlangserver",
                "biome",
                "vue_ls",
                "svls",
                "emmet_ls",
                "bashls",
                "clangd",
                "cmake",
                "htmx",
                "cssmodules_ls",
                "dockerls",
                "docker_compose_language_service",
                "html",
                "jsonls",
                "pyre",
                "pylsp",
                "pyright",
                "rust_analyzer",
                "sqlls",
                "ts_ls",
                "cssls",
                "css_variables",
                "prismals",
                "tailwindcss",
                "taplo",
                "zls",
                "solidity",
                "solidity_ls_nomicfoundation",
                "asm_lsp",
                "yamlls",
                "lemminx",
                "texlab",
                -- "glslls",
                "glsl_analyzer",
                "jdtls",
                "intelephense",
                "lua_ls",
            },
        }
    }

}
